### ISSUE TITLE
Update About us Section

### ISSUE THREAD

**Issue by kemcake** [bitnami/cabin#60]
![simulator screen shot 10 aug 2017 14 29 01](https://user-images.githubusercontent.com/4311124/29192998-6b2b76d6-7dd8-11e7-98df-e52db8c859e0.png)

@sebgoa This might be updated as well? To what?

**Comment by kemcake** [comment]
And I would add something to mention that "Cabin is open sourced!" 🙌

**Comment by sebgoa** [comment]
so we need to switch to bitnami (at least because we need to keep publishing the app):

* bitnami logo
* @bitnami
* kubernetes@bitnami.com
* https://bitnami.com

and the issues link should go to https://github.com/bitnami/cabin/issues

And indeed had a link to the open source repo: https://github.com/bitnami/cabin

**Comment by kemcake** [comment]
I'll add this in the 0.4.0 since I needed to update the build anyway.
